from pysine import sine
import time

c = 260
csharp = 275
d = 292
dsharp = 309
e = 328
f = 347
fsharp = 368
g = 390
gsharp = 413
a = 437
asharp = 463
b = 491
highc = 520

def elasticheart():
    sine(frequency=a, duration=0.25)
    sine(frequency=a, duration=0.25)
    sine(frequency=a, duration=0.25)
    sine(frequency=e, duration=0.25)
    sine(frequency=e, duration=0.5)
    sine(frequency=csharp, duration=0.25)
    sine(frequency=gsharp, duration=0.25)
    sine(frequency=gsharp, duration=0.5)
    sine(frequency=fsharp, duration=0.25)
    time.sleep(0.25)
    sine(frequency=gsharp, duration=0.5)
    sine(frequency=gsharp, duration=0.25)
    sine(frequency=fsharp, duration=0.25)
    sine(frequency=fsharp, duration=0.25)
    sine(frequency=gsharp, duration=0.25)
    sine(frequency=gsharp, duration=0.25)
    sine(frequency=fsharp, duration=0.25)
    sine(frequency=a, duration=0.5)
    sine(frequency=b, duration=0.25)
    time.sleep(0.25)
    sine(frequency=a, duration=0.25)
    sine(frequency=a, duration=0.25)
    sine(frequency=a, duration=0.25)
    sine(frequency=e, duration=0.25)
    sine(frequency=e, duration=0.25)
    sine(frequency=csharp, duration=0.25)
    sine(frequency=csharp, duration=0.25)
    sine(frequency=fsharp, duration=0.25)
    sine(frequency=gsharp, duration=0.5)
    time.sleep(0.25)
    sine(frequency=gsharp, duration=0.25)
    sine(frequency=gsharp, duration=0.25)
    sine(frequency=gsharp, duration=0.25)
    sine(frequency=gsharp, duration=0.25)
    sine(frequency=fsharp, duration=0.25)
    sine(frequency=fsharp, duration=0.25)
    sine(frequency=gsharp, duration=0.25)
    sine(frequency=gsharp, duration=0.25)
    sine(frequency=fsharp, duration=0.25)
    sine(frequency=a, duration=0.5)
    time.sleep(0.25)
    sine(frequency=e, duration=0.25)
    sine(frequency=e, duration=0.25)
    sine(frequency=e, duration=0.25)
    sine(frequency=e, duration=0.25)
    sine(frequency=e, duration=0.25)
    sine(frequency=e, duration=0.25)
    sine(frequency=e, duration=0.25)
    sine(frequency=e, duration=0.25)
    sine(frequency=csharp*2, duration=0.25)
    sine(frequency=csharp*2, duration=0.25)
    sine(frequency=b, duration=0.5)
    time.sleep(0.25)
    sine(frequency=gsharp, duration=0.25)
    sine(frequency=gsharp, duration=0.25)
    sine(frequency=fsharp, duration=0.25)
    sine(frequency=fsharp, duration=0.25)
    sine(frequency=gsharp, duration=0.25)
    sine(frequency=gsharp, duration=0.25)
    sine(frequency=fsharp, duration=0.25)
    sine(frequency=a, duration=0.5)
    time.sleep(0.25)
    sine(frequency=a, duration=0.25)
    sine(frequency=a, duration=0.25)
    sine(frequency=a, duration=0.25)
    sine(frequency=e, duration=0.25)
    sine(frequency=e, duration=0.5)
    sine(frequency=csharp, duration=0.25)
    sine(frequency=gsharp, duration=0.25)
    sine(frequency=gsharp, duration=0.5)
    time.sleep(0.25)
    sine(frequency=gsharp, duration=0.5)
    sine(frequency=gsharp, duration=0.25)
    sine(frequency=fsharp, duration=0.25)
    sine(frequency=fsharp, duration=0.25)
    sine(frequency=gsharp, duration=0.25)
    sine(frequency=gsharp, duration=0.25)
    sine(frequency=fsharp, duration=0.25)
    sine(frequency=fsharp, duration=0.5)
    time.sleep(1.0)

    sine(frequency=fsharp, duration=0.5)
    sine(frequency=e, duration=0.5)
    sine(frequency=csharp, duration=0.5)
    sine(frequency=e, duration=0.5)
    sine(frequency=e, duration=0.5)
    sine(frequency=fsharp, duration=0.5)
    sine(frequency=gsharp, duration=4.0)
    sine(frequency=fsharp, duration=0.5)
    time.sleep(0.25)
    sine(frequency=fsharp, duration=0.5)
    sine(frequency=e, duration=0.5)
    sine(frequency=csharp, duration=0.5)
    sine(frequency=csharp, duration=0.5)
    sine(frequency=e, duration=0.5)
    sine(frequency=fsharp, duration=0.5)
    sine(frequency=gsharp, duration=4.0)
    sine(frequency=fsharp, duration=0.5)
    time.sleep(0.25)
    sine(frequency=fsharp, duration=0.5)
    sine(frequency=fsharp, duration=0.25)
    sine(frequency=d, duration=0.25)
    sine(frequency=a, duration=0.25)
    sine(frequency=a, duration=0.5)
    sine(frequency=e, duration=0.125)
    sine(frequency=e, duration=0.125)
    sine(frequency=e, duration=0.125)
    sine(frequency=a, duration=0.125)
    sine(frequency=a, duration=0.125)
    sine(frequency=gsharp, duration=2.0)



elasticheart()
